# fly.toml app configuration file generated for nhl-plotter-basic on 2024-06-13T22:36:59+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nhl-plotter-basic'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
